#! /usr/bin/env php

<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Uposthapon\ConvertCommand;

$app = new Application('Uposthapon', '0.1.0');

$app->add(new ConvertCommand);

$app->run();
