#! /usr/bin/env php

<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

use Symfony\Component\Console\Application;
use Uposthapon\ConvertCommand;

$app = new Application('Uposthapon', '1.0.6');

$app->add(new ConvertCommand);

$app->run();
